ThirdNote/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace ThirdNote.Models
{
    public class Tag
    {
        public int ID { get; set; }
        public string Label { get; set; }
        public string Lable_fa { get; set; }
        public string Lable_en { get; set; }

        public virtual ICollection<NoteTag> NoteTags { get; set; }
    }


    public class NoteTag
    {
        public int ID { get; set; }
        //[Key, Column(Order = 1)]
        //public int TagId { get; set; }
        //[Key, Column(Order = 2)]
        //public int NoteId { get; set; }

        public int NoteID { get; set; }
        public Note Note { get; set; }

        public int TagID { get; set; }
        public Tag Tag { get; set; }

        public NoteTag(Note note, Tag tag)
        {
            this.Note = note;
            this.Tag = tag;
        }

        public NoteTag()
        {

        }
    }
}

ThirdNote/Models/__Tag.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThirdNote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
    
        public virtual ICollection<Note> Notes { get; set; }
    }
}

ThirdNote/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThirdNote.Models;
using ThirdNote.ViewModels;
using Markdig;
using Humanizer;
using System.Globalization;
using System.Text.RegularExpressions;

namespace ThirdNote.Controllers
{
    [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)]
    public class NoteController : Controller
    {
        public static int ACCORDION_NOTE_ID = 4113;
        public static int REF_TAG_ID = 1049;
        private readonly NotebookDbContext db = new NotebookDbContext();
        private readonly MarkdownPipeline pipeline = App_Start.MarkdownConfig.GetPipeline();

        // GET: Note
        public ActionResult Index(string sortOrder)
        {
            Home NoteIndexViewData = new Home()
            {
                Private = db.Notes.OrderByDescending(n => n.WrittenDate),
                Sorted =  db.Notes.Where(n => !n.Hidden).OrderByDescending(n => n.WrittenDate)
                //Sorted = db.Notes.Where(n => !n.Hidden)
            };
            if (db.Relapses.Count() > 0)
            {
                var dates = db.Relapses.OrderByDescending(r => r.Date).Select(r=>r.Date).ToList();
                var recentRelapseDate = DateTime.Now;
                List<int> Strikes = new List<int>();
                foreach (var item in dates)
                {
                    int offset = (recentRelapseDate - item).Days;
                    Strikes.Add(offset);
                    recentRelapseDate = item;
                }
                //Strikes.Reverse();
                NoteIndexViewData.Strikes = Strikes;
                //indexViewData.LastStrike = (DateTime.Now - db.Relapses.OrderByDescending(r => r.Date).First().Date).Days;
                //System.Diagnostics.Debug.WriteLine(dates);
                //System.Diagnostics.Debug.WriteLine(Strikes);
            }
            else
            {
                NoteIndexViewData.Strikes = new List<int> { 0 };
            }
            //return View(db.Notes.OrderByDescending(n => n.WrittenDate).ThenByDescending(n => n.Id).ToList());
            var notes = db.Notes.Where(n => !n.Hidden);

            switch (sortOrder)
            {
                case "name":
                    notes = notes.OrderBy(n => n.Name).ThenByDescending(n => n.WrittenDate);
                    break;
                case "pin":
                    notes = notes.OrderByDescending(n => n.Pin).ThenByDescending(n => n.WrittenDate);
                    break;
                case "date":
                    notes = notes.OrderBy(n => n.WrittenDate).ThenBy(n => n.Id);
                    break;
                case "date_desc":
                    notes = notes.OrderByDescending(n => n.WrittenDate).ThenByDescending(n => n.Id);
                    break;
                case "likes":
                    notes = notes.OrderByDescending(n => n.ViewCount).ThenByDescending(n => n.WrittenDate);
                    break;
                case "private":
                    notes = db.Notes.OrderByDescending(n => n.Hidden).ThenByDescending(n => n.WrittenDate);
                    break;
                case "markdown":
                    notes = notes.OrderByDescending(n => n.Markdown).ThenByDescending(n => n.WrittenDate);
                    break;
                default:
                    notes = notes.OrderByDescending(n => n.WrittenDate);
                    break;
            }
            NoteIndexViewData.Sorted = notes;
            return View(NoteIndexViewData);
        }

        // GET: Note/List
        public ActionResult List(string sortOrder) 
        {
            Home indexViewData = new Home()
            {
                Private = db.Notes.OrderByDescending(n => n.Hidden).OrderByDescending(n=>n.WrittenDate),
                Sorted = db.Notes.Where(n => !n.Hidden).OrderByDescending(n => n.WrittenDate)
                //Sorted = db.Notes.Where(n => !n.Hidden)
            };
            var notes = db.Notes.Where(n => !n.Hidden);

            switch (sortOrder)
            {
                case "name":
                    notes = notes.OrderBy(n => n.Name).ThenByDescending(n => n.WrittenDate);
                    break;
                case "pin":
                    notes = notes.OrderByDescending(n => n.Pin).ThenByDescending(n => n.WrittenDate);
                    break;
                case "date":
                    notes = notes.OrderBy(n => n.WrittenDate).ThenBy(n => n.Id);
                    break;
                case "date_desc":
                    notes = notes.OrderByDescending(n => n.WrittenDate).ThenByDescending(n => n.Id);
                    break;
                case "likes":
                    notes = notes.OrderByDescending(n => n.ViewCount).ThenByDescending(n => n.WrittenDate);
                    break;
                case "markdown":
                    notes = notes.OrderByDescending(n => n.Markdown).ThenByDescending(n => n.WrittenDate);
                    break;
                default:
                    notes = notes.OrderByDescending(n => n.WrittenDate);
                    break;
            }
            return View(notes.ToList());
            //return View(db.Notes.OrderByDescending(n => n.WrittenDate).ThenByDescending(n => n.Id).Where(p => !p.Hidden).ToList());
            //return View(db.Notes.OrderByDescending(n => n.ViewCount).ThenByDescending(n => n.WrittenDate));
        }

        // GET: Note/Details/5
        public ActionResult Details(string name)
        {
            if (name == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Where(n=>n.Name==name).SingleOrDefault();
            if (note == null)
            {
                return HttpNotFound(name + " not found");
            }
            // Like
            {
                note.ViewCount += 1;
                db.SaveChanges();
            }
            ViewBag.Tags = db.NoteTags.Where(nt => nt.NoteID == note.Id)
                .Join(db.Tags, 
                nt => nt.TagID, 
                t => t.ID, 
                (nt, t) => t);

            // stitching notes
            string snpattern = @"\bsn#\w{8}\b";
            note.Text = Regex.Replace(note.Text, snpattern, delegate (Match match)
            {
                string nName = (match.Value.Split('#').Last());
                Note x = db.Notes.Where(n => n.Name == nName).SingleOrDefault();
                if(x != null)
                {
                    string nText = x.Text;//String.Format("{0}[n#{1}]", db.Notes.Find(nId).Text, nId);
                    return nText + "n#" + nName;
                }
                return nName;
                //return (db.Notes.Find(nId).Markdown && !note.Markdown ? Markdown.ToHtml(note.Text, pipeline) : nText);
            });
            if (note.Markdown)
            {
                var result = Markdown.ToHtml(note.Text, pipeline);
                note.Text = result;
            } else
            {
                note.Text = HttpUtility.HtmlEncode(note.Text);
            }


            string npattern = @"\b(?<=n#)\w{8}\b";
            HashSet<Note> PNotes = new HashSet<Note>();
            Match mc = Regex.Match(note.Text, npattern, RegexOptions.IgnoreCase);
            while (mc.Success)
            {
                Note x = db.Notes.Where(n => n.Name == mc.Value).SingleOrDefault();
                if (x != null)
                {
                    PNotes.Add(x);
                }
                mc = mc.NextMatch();
            }
            ViewBag.PNotes = PNotes;

            string idpattern = @"\b(?<=n#)" + note.Name + @"\b";
            HashSet<Note> CNotes = new HashSet<Note>();
            // CNotes (Child Notes) are referring to this note
            foreach (Note no in db.Notes)
            {
                Match match = Regex.Match(no.Text, idpattern, RegexOptions.IgnoreCase);
                if (match.Success)
                {
                    CNotes.Add(no);
                }
            }
            CNotes.RemoveWhere(n => n.Id == note.Id);  // remove self-citation
            ViewBag.CNotes = CNotes.ToArray();

            // Convert each reference to badge link
            string npatternFull = @"\bn#\w{8}\b";
            note.Text = Regex.Replace(note.Text, npatternFull, delegate (Match match)
            {
                string nName = match.Value.Split('#').Last();
                Note x = db.Notes.Where(n => n.Name == nName).SingleOrDefault();
                if(x != null)
                {
                    string nTitle = x.Title;
                    string sub = "<a id='badge-link bg-gradient' href='/Note/Details/" + nName + "'><span class='badge text-black shadow-sm'><i class='fa fa-hashtag'></i>" + nName + "</span></a>";
                    //string sub = string.Format("<button type='button' class='badge bg-info' data-bs-toggle='tooltip' data-bs-placement='bottom' title='{1}'><a href='/Note/Details/{0}' class=''>#{2}</a></ button >", nName, nTitle, nName);
                    return sub;
                }
                return match.Value;
            });
            //ViewBag.TimeAgo = note.WrittenDate.Humanize(false,null,new CultureInfo("fa"));
            ViewBag.TimeAgo = note.WrittenDate.Humanize(false);
            return View(note);
        }

        // GET: Note/Create
        [HttpGet]
        [ValidateInput(false)]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Note/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateInput(false)]

ThirdNote/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThirdNote.Models;
using System.Data.Entity.Migrations;
using System.Data.Entity;

namespace ThirdNote.Controllers
{
    [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)] 
    public class TagController : Controller
    {
        private static readonly NotebookDbContext db = new NotebookDbContext();

        // GET: Tag
        public ActionResult Index(string sort, string columns, string lang)
        {
            using (var ctx = new NotebookDbContext())
            {
                // delete tags with no reference in noteTag 
                var OrphanTags = ctx.Tags.Where(t => t.NoteTags.Count == 0);
                //db.Tags.RemoveRange(OrphanTags);
                foreach (var item in OrphanTags)
                    ctx.Entry(item).State = EntityState.Deleted;
                ctx.SaveChanges();

                switch (sort)
                {
                    case "alpha":
                        return View(ctx.Tags.Include(t=>t.NoteTags).OrderBy(tag => "en".Equals(lang) ? tag.Lable_en : tag.Lable_fa).ToList());
                    case "num":
                        return View(ctx.Tags.Include(t => t.NoteTags).OrderByDescending(tag => tag.NoteTags.Count)
                            .ThenBy(tag => "en".Equals(lang)?tag.Lable_en:tag.Lable_fa).ToList());
                    default:
                        return View(ctx.Tags.Include(t => t.NoteTags).OrderBy(tag => "en".Equals(lang) ? tag.Lable_en : tag.Lable_fa).ToList());
                }
            }
        }

        // GET: Tag/Details/5
        [OutputCacheAttribute(VaryByParam = "*", Duration = 0, NoStore = true)] // will disable caching for Index only
        public ActionResult Details(int id)
        {
            ViewBag.Tag = db.Tags.Find(id);
            var data = db.Notes.Include(s => s.NoteTags)
                               .Where(n => n.NoteTags.Any(nt => nt.TagID == id))
                               .Where(n => !n.Hidden)
                               .OrderByDescending(n => n.WrittenDate)
                               .AsNoTracking();
            return View(data);
        }

        // GET: Tag/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tag/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Tag/Edit/5
        public ActionResult Edit(int id)
        {
            Tag tag = db.Tags.Find(id);
            return View(tag);
        }

        // POST: Tag/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "ID,Label,Lable_en,Lable_fa")] Tag tag, FormCollection formCollection)
        {
            if (ModelState.IsValid)
            {
                tag.Label = formCollection["Label"].ToString();
                tag.Lable_en = formCollection["Lable_en"].ToString();
                tag.Lable_fa = formCollection["Lable_fa"].ToString();
                //db.Tags.AsNoTracking().Where(t => t.ID == tag.ID);
                //db.Entry(tag).State = System.Data.Entity.EntityState.Modified;
                db.Set<Tag>().AddOrUpdate(tag);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = tag.ID });
            }
            return View();
        }

        // GET: Tag/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Tag/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Search()
        {
            var tagLabels = db.Tags.Select(t => t.Label).ToList();
            return Json(tagLabels, JsonRequestBehavior.AllowGet);
        }  
    }
}

ThirdNote/Views/Tag/Details.cshtml
@model IEnumerable<ThirdNote.Models.Note>

@{
    ViewBag.Title = "Tag | " + (string.IsNullOrEmpty(ViewBag.Tag.Lable_en) ? ViewBag.Tag.Label : ViewBag.Tag.Lable_en).ToLower();
    //"Tag " + ViewBag.Tag.Lable_en;
}


<div class="d-flex flex-row justify-content-start align-items-center mb-3">
    <a class="btn shadow-none" href="/Tag/Edit/@ViewBag.Tag.ID"> <i class="fa fa-edit fa-2x fa-fw"></i> </a>
    <div style="margin-bottom:0;" class="ms-3">
        <p class="btn btn-outline-secondary btn-dark text-dark rounded rounded-3 me-1 disabled">@ViewBag.Tag.Lable_fa</p> :
        <p class="btn btn-outline-secondary btn-dark text-dark rounded rounded-3 ms-1 disabled">@ViewBag.Tag.Lable_en</p>
    </div>
</div>

<div class="row">
    <div class="col-12">
        @*####################( Only Tagged Notes )####################*@
        @Html.Partial("~/Views/Note/List.cshtml", Model)
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/dir-auto")
}

ThirdNote/Views/Tag/Edit.cshtml
@model ThirdNote.Models.Tag

@{
    ViewBag.Title = "Tag Edit";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            @*####################( Vertical Control Buttons )####################*@
            <div class="col-1 d-flex flex-column align-items-start justify-content-between">
                @*##########( Back Button )##########*@
                <p class="btn btn-link link-dark" onclick="window.history.go(-1); return false;"><i class="fa fa-arrow-square-left fa-2x fa-fw" title="Back"></i></p>
                @*###############( Save Button )###############*@
                <button type="submit" class="btn btn-link link-dark" style="box-shadow:none;">
                    <i class="fa fa-save fa-2x fa-fw"></i>
                </button>
            </div>
            <div class="col-8">
                @Html.HiddenFor(model => model.ID)


                <div class="form-group row mb-3">
                    @Html.LabelFor(model => model.Label, htmlAttributes: new { @class = "control-label col-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Label, new { htmlAttributes = new { @class = "form-control dir-auto" } })
                        @Html.ValidationMessageFor(model => model.Label, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row mb-3">
                    @Html.LabelFor(model => model.Lable_en, htmlAttributes: new { @class = "control-label col-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Lable_en, new { htmlAttributes = new { @class = "form-control dir-auto" } })
                        @Html.ValidationMessageFor(model => model.Lable_en, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group row ">
                    @Html.LabelFor(model => model.Lable_fa, htmlAttributes: new { @class = "control-label col-2" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Lable_fa, new { htmlAttributes = new { @class = "form-control dir-auto" } })
                        @Html.ValidationMessageFor(model => model.Lable_fa, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ThirdNote/Views/Tag/Index.cshtml
@model IEnumerable<ThirdNote.Models.Tag>

@{
    ViewBag.Title = "Tags";
}


@{
    var X = ThirdNote.Controllers.NoteController.ACCORDION_NOTE_ID;
    var L = Request.Params["lang"];
    var Z = Request.Params["sort"];
    var K = Request.Params["columns"].AsInt();
    foreach (ThirdNote.Models.Tag item in Model)
    {
        item.Lable_en = string.IsNullOrEmpty(item.Lable_en) ? "" : item.Lable_en.ToLower();
    }
}


<i class="mx-3">
    Lang:
    <small>@Html.ActionLink("en", "Index", new { lang = "en", sort = Z, columns = K }, new { @class = "btn btn-outline-info btn-sm" })</small>
    <small>@Html.ActionLink("fa", "Index", new { lang = "fa", sort = Z, columns = K }, new { @class = "btn btn-outline-info btn-sm active" })</small>
</i>

<i class="mx-3">
    Sort:
    <small>@Html.ActionLink("alpha", "Index", new { lang = L, sort = "alpha", columns = K }, new { @class = "btn btn-outline-info btn-sm active" })</small>
    <small>@Html.ActionLink("num", "Index", new { lang = L, sort = "num", columns = K }, new { @class = "btn btn-outline-info btn-sm" })</small>
    <small>@Html.ActionLink("grp", "Details", "Note", new { id = X } , new { @class = "btn btn-outline-info btn-sm" })</small> 
</i>

<i class="mx-3">
    Columns:
    <small>@Html.ActionLink("1", "Index", new { lang = L, sort = Z, columns = 1 }, new { @class = "btn btn-outline-info btn-sm" })</small> 
    <small>@Html.ActionLink("2", "Index", new { lang = L, sort = Z, columns = 2 }, new { @class = "btn btn-outline-info btn-sm" })</small> 
    <small>@Html.ActionLink("3", "Index", new { lang = L, sort = Z, columns = 3 }, new { @class = "btn btn-outline-info btn-sm" })</small> 
    <small>@Html.ActionLink("4", "Index", new { lang = L, sort = Z, columns = 4 }, new { @class = "btn btn-outline-info btn-sm active" })</small>
</i>
<hr />

@if (K == 1)
{
    <div class="row">
        @foreach (var tag in Model)
        {
            <div class="col-12">
                @if (!String.IsNullOrEmpty(Request.Params["lang"]) && Request.Params["lang"].Equals("en"))
                {
                    <a href="\Tag\Details\@tag.ID"> @tag.Lable_en (@tag.NoteTags.Count)</a>
                }
                else
                {
                    <a href="\Tag\Details\@tag.ID"> @tag.Lable_fa (@tag.NoteTags.Count)</a>
                }
            </div>
        }
    </div>
}
else if (K == 2)
{
<div class="row">

    @foreach (var group in Model.GroupBy(t => t.Label).OrderByDescending(g => g.Count()).Select(g => new { key = g.Key, count = g.Count() }))
    {
        <div class="col-6">

            <p class="text-secondary mt-2">@group.key (@group.count)</p>
        @foreach (var tag in Model.Where(t => t.Label == group.key))
        {
            <div class="col-12">
                @if (!String.IsNullOrEmpty(Request.Params["lang"]) && Request.Params["lang"].Equals("en"))
                {
                    <a href="\Tag\Details\@tag.ID"> @tag.Lable_en (@tag.NoteTags.Count)</a>
                }
                else
                {
                    <a href="\Tag\Details\@tag.ID"> @tag.Lable_fa (@tag.NoteTags.Count)</a>
                }
            </div>
        }

        </div>
    }
</div>
}
else if (K == 3)
{
    <div class="row">
        <div class="col-4">
            <div class="row">
                @foreach (var tag in Model.Take((Model.Count() + 2) / 3))
                {
                    <div class="col-12">
                        @if (!String.IsNullOrEmpty(Request.Params["lang"]) && Request.Params["lang"].Equals("en"))
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_en (@tag.NoteTags.Count)</a>
                        }
                        else
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_fa (@tag.NoteTags.Count)</a>
                        }
                    </div>
                }
            </div>
        </div>
        <div class="col-4">
            <div class="row">
                @foreach (var tag in Model.Skip((Model.Count() + 2) / 3).Take((Model.Count() + 2) / 3))
                {
                    <div class="col-12">
                        @if (!String.IsNullOrEmpty(Request.Params["lang"]) && Request.Params["lang"].Equals("en"))
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_en (@tag.NoteTags.Count)</a>
                        }
                        else
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_fa (@tag.NoteTags.Count)</a>
                        }
                    </div>
                }
            </div>
        </div>
        <div class="col-4">
            <div class="row">
                @foreach (var tag in Model.Skip(2 * (Model.Count() + 2) / 3))
                {
                    <div class="col-12">
                        @if (!String.IsNullOrEmpty(Request.Params["lang"]) && Request.Params["lang"].Equals("en"))
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_en (@tag.NoteTags.Count)</a>
                        }
                        else
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_fa (@tag.NoteTags.Count)</a>
                        }
                    </div>
                }
            </div>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-3">
            <div class="row">
                @foreach (var tag in Model.Take((Model.Count() + 3) / 4))
                {
                    <div class="col-12">
                        @if (!String.IsNullOrEmpty(Request.Params["lang"]) && Request.Params["lang"].Equals("en"))
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_en (@tag.NoteTags.Count)</a>
                        }
                        else
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_fa (@tag.NoteTags.Count)</a>
                        }
                    </div>
                }
            </div>
        </div>
        <div class="col-3">
            <div class="row">
                @foreach (var tag in Model.Skip((Model.Count() + 3) / 4).Take((Model.Count() + 3) / 4))
                {
                    <div class="col-12">
                        @if (!String.IsNullOrEmpty(Request.Params["lang"]) && Request.Params["lang"].Equals("en"))
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_en (@tag.NoteTags.Count)</a>
                        }
                        else
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_fa (@tag.NoteTags.Count)</a>
                        }
                    </div>
                }
            </div>
        </div>
        <div class="col-3">
            <div class="row">
                @foreach (var tag in Model.Skip(2 * (Model.Count() + 3) / 4).Take((Model.Count() + 3) / 4))
                {
                    <div class="col-12">
                        @if (!String.IsNullOrEmpty(Request.Params["lang"]) && Request.Params["lang"].Equals("en"))
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_en (@tag.NoteTags.Count)</a>
                        }
                        else
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_fa (@tag.NoteTags.Count)</a>
                        }
                    </div>
                }
            </div>
        </div>
        <div class="col-3">
            <div class="row">
                @foreach (var tag in Model.Skip(3 * (Model.Count() + 3) / 4))
                {
                    <div class="col-12">
                        @if (!String.IsNullOrEmpty(Request.Params["lang"]) && Request.Params["lang"].Equals("en"))
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_en (@tag.NoteTags.Count)</a>
                        }
                        else
                        {
                            <a href="\Tag\Details\@tag.ID"> @tag.Lable_fa (@tag.NoteTags.Count)</a>
                        }
                    </div>
                }
            </div>
        </div>
    </div>
}


<br />

<script>

    var getUrlParameter = function getUrlParameter(sParam) {
        var sPageURL = window.location.search.substring(1),
            sURLVariables = sPageURL.split('&'),
            sParameterName,
            i;

        for (i = 0; i < sURLVariables.length; i++) {
            sParameterName = sURLVariables[i].split('=');
            if (sParameterName[0] === sParam) {
                return sParameterName[1] === undefined ? true : decodeURIComponent(sParameterName[1]);
            }
        }
        return false;
    };

    const btn = document.getElementsByClassName("btn-sm");
    for (let i = 0; i < btn.length; i++) {
        if (btn[i].textContent == getUrlParameter("lang"))
            btn[i].classList.add("active");
        else if (btn[i].textContent == getUrlParameter("sort"))
            btn[i].classList.add("active");
        else if (btn[i].textContent == getUrlParameter("columns"))
            btn[i].classList.add("active");
        else if (btn[i].classList.contains("active"))
            btn[i].classList.toggle("active");
    }
</script>