ThirdNote/ViewModels/Home.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ThirdNote.Models;

namespace ThirdNote.ViewModels
{
    public class Home
    {
        public IEnumerable<Note> Private { get; set; }
        public IEnumerable<Note> Sorted { get; set; }
        public List<int> Strikes { get; set; }
    }
}

ThirdNote/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThirdNote.ViewModels;
using ThirdNote.Models;

namespace ThirdNote.Controllers
{
    public class HomeController : Controller
    {

        private NotebookDbContext db = new NotebookDbContext();

        public ActionResult Index(string sortOrder)
        {
            Home HomeViewData = new Home()
            {
                Private = db.Notes.Where(n => !n.Hidden).OrderByDescending(n => n.WrittenDate),
                Sorted = db.Notes.Where(n => !n.Hidden).OrderByDescending(n => n.WrittenDate)
                //Sorted = db.Notes.Where(n => !n.Hidden)
            };
            var notes = db.Notes.Where(n => !n.Hidden);

            switch (sortOrder)
            {
                case "name":
                    notes = notes.OrderBy(n => n.Name).ThenByDescending(n => n.WrittenDate);
                    break;
                case "pin":
                    notes = notes.OrderByDescending(n => n.Pin).ThenByDescending(n => n.WrittenDate);
                    break;

                case "date":
                    notes = notes.OrderBy(n => n.WrittenDate);
                    break;
                case "date_desc":
                    notes = notes.OrderByDescending(n => n.WrittenDate);
                    break;
                case "likes":
                    notes = notes.OrderByDescending(n => n.ViewCount).ThenByDescending(n => n.WrittenDate);
                    break;
                case "markdown":
                    notes = notes.OrderByDescending(n => n.Markdown).ThenByDescending(n => n.WrittenDate);
                    break;
                default:
                    notes = notes.OrderByDescending(n => n.WrittenDate);
                    break;
            }
            HomeViewData.Sorted = notes;
            return View(HomeViewData);

            //return RedirectToAction("Index", "Note");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ThirdNote/Controllers/RelapseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThirdNote.Models;

namespace ThirdNote.Controllers
{
    public class RelapseController : Controller
    {
        private NotebookDbContext db = new NotebookDbContext();

        // GET: Relapses
        public ActionResult Index()
        {
            return View(db.Relapses.ToList());
        }

        // GET: Relapses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relapse relapse = db.Relapses.Find(id);
            if (relapse == null)
            {
                return HttpNotFound();
            }
            return View(relapse);
        }

        // GET: Relapses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Relapses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Subject,Date,Message")] Relapse relapse, FormCollection formCollection)
        {
            if (ModelState.IsValid)
            {
                if (relapse.Message == null)
                {
                    relapse.Message = "";
                }
                if (DateTime.TryParse(formCollection["MyDate"], out DateTime dt))
                {
                    relapse.Date = DateTime.Parse(formCollection["MyDate"]);
                }
                else
                {
                    relapse.Date = DateTime.Now;
                }
                

                db.Relapses.Add(relapse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(relapse);
        }

        // GET: Relapses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relapse relapse = db.Relapses.Find(id);
            if (relapse == null)
            {
                return HttpNotFound();
            }
            return View(relapse);
        }

        // POST: Relapses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Subject,Date,Message")] Relapse relapse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(relapse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(relapse);
        }

        // GET: Relapses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relapse relapse = db.Relapses.Find(id);
            if (relapse == null)
            {
                return HttpNotFound();
            }
            return View(relapse);
        }

        // POST: Relapses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Relapse relapse = db.Relapses.Find(id);
            db.Relapses.Remove(relapse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ThirdNote/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ThirdNote/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ThirdNote/Views/Home/Index.cshtml
@model ThirdNote.ViewModels.Home
@*@model IEnumerable<ThirdNote.Models.Note>*@

@{
    ViewBag.Title = "Home";
}




@*<br />*@

<style>
    .table {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
</style>


@Html.Partial("~/Views/Note/List.cshtml", Model.Sorted)

ThirdNote/Views/Home/IronWill.cshtml
@model ThirdNote.ViewModels.Home
<link href="~/Content/css-circular-prog-bar.css" rel="stylesheet" />
@*####################( Style )####################*@
<style>
    .dashboard {
        font-family: 'Times New Roman', Times, serif;
    }

    .iwill {
        border-radius: 50px;
        background-image: linear-gradient(to bottom right, khaki, white);
        font-family: 'Times New Roman', Times, serif;
    }
</style>

@*####################( Dashboard )####################*@

<div class="row justify-content-end dashboard">
    @*##########( New Note Shortcut )##########*@
    <div class="col-6 p-3">
        @* Create Note *@
        <h2>
            <a href="\Note\Create" class="px-2 btn btn-outline btn-outline-success"> <img src="~/Content/addnote.png" style="width:86px; height:auto;"/> </a>
        </h2>
    </div>

    @*##########( Iron Will )##########*@
    <div class="col-6 iwill">
        <div class="row justify-content-end">
            @*##########( Level-up Daily Counter )##########*@
            <div class="col-4">
                @*##########( Milestones )##########*@
                @{
                    List<int> milestones = new List<int> { 0, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987 };
                    int strike = Model.Strikes.First();
                    int nextMile = milestones.Where(m => m > strike).Min();
                    int lastMile = milestones.Where(m => m <= strike).Max();
                    int percent = 100 * (((strike-lastMile) * 24 + DateTime.Now.Hour) * 60 + DateTime.Now.Minute) / (((nextMile-lastMile) * 24 + DateTime.Now.Hour) * 60 + DateTime.Now.Minute);
                    double dpercent = 100.0 * (((strike - lastMile) * 24 + DateTime.Now.Hour) * 60 + DateTime.Now.Minute) / (((nextMile - lastMile) * 24 + DateTime.Now.Hour) * 60 + DateTime.Now.Minute);

                }
                @*#####( Dynamic Tag )#####*@
                @*<div class="progress-circle p60">*@
                <div class="@(percent<=50 ? "progress-circle p"+percent : "progress-circle over50 p"+percent)">
                    <span style="text-shadow: 1px 1px 2px #888888;"><b>@nextMile</b> </span>
                    <div class="left-half-clipper">
                        <div class="first50-bar"></div>
                        <div class="value-bar"></div>
                    </div>
                </div>
            </div>
            @*##########( Badge )##########*@
            <div class="col-8">
                @* Badge *@
                <div style="margin-top:25px;">
                    @*##########( Nickname Titles )##########*@
                    @{
                        string getNikename(int days)
                        {
                            string nike = "Astronaut";
                            if (days >= 987)
                                nike = "Immortal";
                            else if (days >= 610)
                                nike = "King of Will Power";
                            else if (days >= 377)
                                nike = "General";
                            else if (days >= 233)
                                nike = "Colonel";
                            else if (days >= 144)
                                nike = "Commander";
                            else if (days >= 89)
                                nike = "Champion";
                            else if (days >= 55)
                                nike = "Master";
                            else if (days >= 34)
                                nike = "Guardian";
                            else if (days >= 21)
                                nike = "Knight";
                            else if (days >= 13)
                                nike = "Sergeant";
                            else if (days >= 8)
                                nike = "Corporal";
                            else if (days >= 5)
                                nike = "Private";
                            else if (days >= 3)
                                nike = "Soldier";
                            else if (days >= 2)
                                nike = "Warrior";
                            else if (days >= 1)
                                nike = "Man of Courage";
                            return nike;
                        }
                    }
                    <h2>@getNikename(strike)</h2>
                    <h4>
                        You are on a <b style="text-shadow: 2px 2px 4px #ff6a00; ">@Model.Strikes.First() days </b>strike!
                        @*##########( Private Link to relapse history page )##########*@
                        @Html.ActionLink("..", "Index", "Relapse", null, new { @style = "color:#f5f5dd;" })
                    </h4>



                    @*##########( Strikes History )##########*@
                    @*
                        <a href="\Relapse\Create" class="mx-2"> + </a>
                        <div class="d-flex flex-wrap">
                            @foreach (var item in Model.Strikes)
                            {
                                <div class="mx-2" style="text-shadow: 2px 2px 4px #888888;"> @item </div>
                            }
                        </div>
                    *@
                </div>
            </div>
        </div>
    </div>
</div>